#!/usr/bin/env bash
# A Bash script that pings an IP address as an argument. Requirements:
#+ Acepts a string as an argument
#+ Display 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no argument passed
#+ Pings the IP 5 times

if [ "$#" -eq 0 ]; then 
	echo "Usange: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
